### ISSUE TITLE
Right clicking on a cow with a teapot makes the teapot disapear.

### ISSUE THREAD

**Issue by thisisACat5** [elucent/SimplyTea#15] opened 2019-11-25 20:52 UTC
Tell me if i need to provide something other than Minecraft version(1.14.4)!

**Comment by KnightMiner** [comment] 2019-11-25 21:07
Duplicate of #13. It has not been high priority to release.

You should provide mod and Forge versions at minimum for the record.

**Closed as completed by KnightMiner** 2019-11-25 21:07 UTC
Labels: duplicate
