### ISSUE TITLE
[Cross-mod compatibility feature] Compat with inspirations

### ISSUE THREAD

**Issue by dkmk100** [elucent/SimplyTea#45] opened 2021-11-06 23:48 UTC
Basically, allow for filling a teapot with milk if the cauldron has milk, and don't allow picking up other random fluids. Inspirations changes cauldrons to hold any fluid.

**Comment by KnightMiner** [comment] 2022-10-17 22:10
Closing as a duplicate of #46, as working with other fluid tanks would work with inspirations

**Closed as completed by KnightMiner** 2022-10-17 22:10 UTC
Labels: duplicate
